In [7]:
import numpy as np
array1=np.array([1,2,3])
array1
type(array1)

numpy.ndarray

In [9]:
array2=np.array([[1,2,3],[4,5,6]])
array2
type(array2)

numpy.ndarray

In [33]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [17]:
b=np.array([[7.0,8.5,9.5],[10.5,5.5,6.5]])
print(b)

[[ 7.   8.5  9.5]
 [10.5  5.5  6.5]]


In [18]:
a.shape

(3,)

In [19]:
b.shape

(2, 3)

In [44]:
#This will show the size of the array
a.size

3

In [34]:
#this will show the dtype of the elements
a.dtype

dtype('int32')

In [41]:
#This will show number of bytes of a individual element
a.itemsize

4

In [43]:
#This will show the number of bytes of all the elements[4*3]
a.nbytes

12

In [51]:
b.size

6

In [52]:
b.shape

(2, 3)

In [48]:
b.dtype

dtype('float64')

In [53]:
#This will show number of bytes of a individual element
b.itemsize

8

In [50]:
b.nbytes

48

In [47]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


accessing the elements

In [68]:
#This will show the 1st row
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [69]:
#This will show the 2nd column of 1st row
a[0,1]

2

In [73]:
#This will show the 5Th column
a[:,4]

array([ 5, 12])

In [74]:
a[:,4]=[100,200]

In [75]:
#This will replace the 5Th column with [100,200]
a

array([[  1,   2,   3,   4, 100,   6,   7],
       [  8,   9,  10,  11, 200,  13,  14]])

In [80]:
a[1,1:6:2]

array([ 9, 11, 13])

In [109]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [112]:
b[1,:,1]=[9,10]
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  9],
        [ 7, 10]]])

In [116]:
b[:,1,:]=[[11,12],[13,14]]
b

array([[[ 1,  2],
        [11, 12]],

       [[11, 12],
        [13, 14]]])

In [139]:
b.dtype

dtype('int32')

In [161]:
#this will give the 1D array of 5 elements with Zero as a element
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [167]:
#This will give the 2 arrays of shape 2/2 with zeros as a elements, dtype will give the array in dtype int32 which will take less memory of 32 bytes
z=np.zeros((2,2,2),dtype='int32')
z

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [168]:
z.dtype

dtype('int32')

In [169]:
#this will give the 5 arrays of shape 2/2 with ones as a element
np.ones((5,2,2),dtype='int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [172]:
#This will give 2d array of shape 5/5 with 8 as elements
np.full((5,5),(8))

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [175]:
#This will give 3 2D arrays of shape of 5/5 with 8 as a elements.
np.full((3,5,5),(8))

array([[[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]],

       [[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]],

       [[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]]])

In [177]:
#This will give array with shape of a array with 4 as a element
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [178]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [179]:
#Random decimal numbers
np.random.rand(4)

array([0.96017342, 0.38163844, 0.30769121, 0.9290119 ])

In [180]:
np.random.rand(3,4)

array([[0.48011582, 0.50925063, 0.23193657, 0.82783741],
       [0.18444494, 0.33912668, 0.38363964, 0.04689653],
       [0.28316554, 0.01283239, 0.596434  , 0.16461322]])

In [181]:
np.random.rand(2,3,4)

array([[[0.51537282, 0.31263813, 0.56302002, 0.74021274],
        [0.50539885, 0.6697472 , 0.89346331, 0.66297388],
        [0.38555324, 0.28032831, 0.17738926, 0.53922637]],

       [[0.4186128 , 0.05465709, 0.83780531, 0.61393024],
        [0.6068371 , 0.37167334, 0.1907186 , 0.48972431],
        [0.44976749, 0.3331702 , 0.38319505, 0.88213658]]])

In [183]:
np.random.random_sample(a.shape)

array([[0.2510207 , 0.46458012, 0.70220855, 0.89482432, 0.36686916,
        0.96472626, 0.60826431],
       [0.7732094 , 0.6431973 , 0.26123006, 0.43438811, 0.33475751,
        0.87076031, 0.00636388]])

In [184]:
np.random.rand(3,4)

array([[0.95868122, 0.54894039, 0.92775823, 0.41851982],
       [0.36530532, 0.06481016, 0.06829687, 0.23222127],
       [0.76105257, 0.70295352, 0.62759752, 0.72112788]])